sudo: required

addons:
  apt:
    packages: haveged

services:
  - docker

language: ruby

rvm:
  - "3.1"

gemfile:
  - "gemfiles/rails_6.1.gemfile"
  - "gemfiles/rails_7.0.gemfile"
  - "gemfiles/rails_7.1.gemfile"

env:
  - CASSANDRA_VERSION=2.2
  - CASSANDRA_VERSION=3.0
  - CASSANDRA_VERSION=3.11

script: script/ci-unit-test

bundler_args: '--without=debug'

matrix:
  exclude:
